[package]
name = "learning-rust-prims"
version = "0.1.0"
authors = ["ayrock-dev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
